-- MySQL Script generated by MySQL Workbench
-- Sun Sep  9 18:15:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ratatouille_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ratatouille_db` ;

-- -----------------------------------------------------
-- Schema ratatouille_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ratatouille_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `ratatouille_db` ;

-- -----------------------------------------------------
-- Table `ratatouille_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratatouille_db`.`product` (
  `code` BIGINT(20) UNSIGNED NOT NULL,
  `product_name` VARCHAR(200) NOT NULL,
  `brand` VARCHAR(200) NOT NULL,
  `url_link` VARCHAR(255) NOT NULL,
  `nutrition_grade_fr` CHAR(1) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ratatouille_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratatouille_db`.`category` (
  `id` MEDIUMINT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `name_UNIQUE` ON `ratatouille_db`.`category` (`name` ASC);


-- -----------------------------------------------------
-- Table `ratatouille_db`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratatouille_db`.`store` (
  `id` MEDIUMINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ratatouille_db`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratatouille_db`.`product_category` (
  `category_id` MEDIUMINT(10) UNSIGNED NOT NULL,
  `product_code` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`category_id`, `product_code`),
  CONSTRAINT `fk_category_has_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `ratatouille_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `ratatouille_db`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_category_has_product_product1_idx` ON `ratatouille_db`.`product_category` (`product_code` ASC);

CREATE INDEX `fk_category_has_product_category_idx` ON `ratatouille_db`.`product_category` (`category_id` ASC);


-- -----------------------------------------------------
-- Table `ratatouille_db`.`product_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratatouille_db`.`product_store` (
  `product_code` BIGINT(20) UNSIGNED NOT NULL,
  `store_id` MEDIUMINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`product_code`, `store_id`),
  CONSTRAINT `fk_product_has_store_product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `ratatouille_db`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_store_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `ratatouille_db`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_has_store_store1_idx` ON `ratatouille_db`.`product_store` (`store_id` ASC);

CREATE INDEX `fk_product_has_store_product1_idx` ON `ratatouille_db`.`product_store` (`product_code` ASC);


-- -----------------------------------------------------
-- Table `ratatouille_db`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ratatouille_db`.`favoris` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `substitute_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_favoris_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ratatouille_db`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoris_product2`
    FOREIGN KEY (`substitute_id`)
    REFERENCES `ratatouille_db`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_favoris_product1_idx` ON `ratatouille_db`.`favoris` (`product_id` ASC);

CREATE INDEX `fk_favoris_product2_idx` ON `ratatouille_db`.`favoris` (`substitute_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
